### ISSUE TITLE
ph4 package builder issue: ['postgresql13-13.10', 'kafka-3.4.0'] fails to build because of missing source

### ISSUE THREAD

**Issue by dcasota** [vmware/photon#1392]
### Describe the bug

['postgresql13-13.10', 'kafka-3.4.0'] fails to build. Source url makes a lookup to .../photon_Sources/1.0/...

```
404 Client Error: Not Found for url: https://packages.vmware.com/photon/photon_sources/1.0/postgresql-13.10.tar.bz2
Traceback (most recent call last):
  File "/photon/support/package-builder/PullSources.py", line 59, in get
    downloadFile(url, destfile)
  File "/photon/support/package-builder/PullSources.py", line 87, in downloadFile
    response.raise_for_status()
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://packages.vmware.com/photon/photon_sources/1.0/postgresql-13.10.tar.bz2
Failed while building package: postgresql13
tail: cannot open '/photon/stage/LOGS/postgresql13-13.10.x86_64/postgresql13.log' for reading: No such file or directory

Missing source: postgresql-13.10.tar.bz2
Traceback (most recent call last):
  File "/photon/support/package-builder/PackageBuilder.py", line 42, in build
    self._buildPackage()
  File "/photon/support/package-builder/PackageBuilder.py", line 79, in _buildPackage
    raise e
  File "/photon/support/package-builder/PackageBuilder.py", line 66, in _buildPackage
    pkgUtils.buildRPMSForGivenPackage(self.sandbox, self.package, self.version,
  File "/photon/support/package-builder/PackageUtils.py", line 125, in buildRPMSForGivenPackage
    self._copySources(sandbox, listSourcesFiles, package, version, sourcePath)
  File "/photon/support/package-builder/PackageUtils.py", line 303, in _copySources
    sourcePath = self._verifyShaAndGetSourcePath(source, package, version)
  File "/photon/support/package-builder/PackageUtils.py", line 276, in _verifyShaAndGetSourcePath
    PullSources.get(package, source, checksum, constants.sourcePath,
  File "/photon/support/package-builder/PullSources.py", line 69, in get
    raise Exception("Missing source: " + source)
Exception: Missing source: postgresql-13.10.tar.bz2
Missing source: postgresql-13.10.tar.bz2
Traceback (most recent call last):
  File "/photon/support/package-builder/WorkerThread.py", line 29, in run
    pkgBuilder.build(pkg, doneList)
  File "/photon/support/package-builder/PackageBuilder.py", line 46, in build
    raise e
  File "/photon/support/package-builder/PackageBuilder.py", line 42, in build
    self._buildPackage()
  File "/photon/support/package-builder/PackageBuilder.py", line 79, in _buildPackage
    raise e
  File "/photon/support/package-builder/PackageBuilder.py", line 66, in _buildPackage
    pkgUtils.buildRPMSForGivenPackage(self.sandbox, self.package, self.version,
  File "/photon/support/package-builder/PackageUtils.py", line 125, in buildRPMSForGivenPackage
    self._copySources(sandbox, listSourcesFiles, package, version, sourcePath)
  File "/photon/support/package-builder/PackageUtils.py", line 303, in _copySources
    sourcePath = self._verifyShaAndGetSourcePath(source, package, version)
  File "/photon/support/package-builder/PackageUtils.py", line 276, in _verifyShaAndGetSourcePath
    PullSources.get(package, source, checksum, constants.sourcePath,
  File "/photon/support/package-builder/PullSources.py", line 69, in get
    raise Exception("Missing source: " + source)
Exception: Missing source: postgresql-13.10.tar.bz2
```

```
2023-02-18 13:38:11,441 - build-kafka-3.4.0 - Building package : kafka
2023-02-18 13:38:13,811 - build-kafka-3.4.0 - 404 Client Error: Not Found for url: https://packages.vmware.com/photon/photon_sources/1.0/kafka-3.4.0-src.tgz
Traceback (most recent call last):
  File "/photon/support/package-builder/PullSources.py", line 59, in get
    downloadFile(url, destfile)
  File "/photon/support/package-builder/PullSources.py", line 87, in downloadFile
    response.raise_for_status()
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://packages.vmware.com/photon/photon_sources/1.0/kafka-3.4.0-src.tgz
2023-02-18 13:38:13,815 - build-kafka-3.4.0 - Failed while building package: kafka
2023-02-18 13:38:13,831 - build-kafka-3.4.0 - 
2023-02-18 13:38:13,832 - build-kafka-3.4.0 - Missing source: kafka-3.4.0-src.tgz
Traceback (most recent call last):
  File "/photon/support/package-builder/PackageBuilder.py", line 42, in build
    self._buildPackage()
  File "/photon/support/package-builder/PackageBuilder.py", line 79, in _buildPackage
    raise e
  File "/photon/support/package-builder/PackageBuilder.py", line 66, in _buildPackage
    pkgUtils.buildRPMSForGivenPackage(self.sandbox, self.package, self.version,
  File "/photon/support/package-builder/PackageUtils.py", line 125, in buildRPMSForGivenPackage
    self._copySources(sandbox, listSourcesFiles, package, version, sourcePath)
  File "/photon/support/package-builder/PackageUtils.py", line 303, in _copySources
    sourcePath = self._verifyShaAndGetSourcePath(source, package, version)
  File "/photon/support/package-builder/PackageUtils.py", line 276, in _verifyShaAndGetSourcePath
    PullSources.get(package, source, checksum, constants.sourcePath,
  File "/photon/support/package-builder/PullSources.py", line 69, in get
    raise Exception("Missing source: " + source)
Exception: Missing source: kafka-3.4.0-src.tgz
```

### Reproduction steps

1. x86_64 build system
2. `git fetch` `git merge origin/4.0` (https://github.com/vmware/photon/commit/dc557b3d5195c05bc107c17f178b9f8f456fff7a)

### Expected behavior

correct url lookup

**Comment by dcasota** [comment]
Retested with https://github.com/vmware/photon/commit/9c43fc6d0f013d442d9a605ec1801423b6a685a3, build make slipstreamed Ph4 iso successfully completes. -> close ticket
