### ISSUE TITLE
Cross-compiling 5.0 branch

### ISSUE THREAD

**Issue by rousku** [vmware/photon#1533]
### Describe the bug

I'm trying to cross-compile 5.0 branch for an aarch64 system on a x86_64 host. The building of packages for x86_64 succeeds but the step that compiles packages for aarch64 fails.

### Reproduction steps

1. set "targetArch" in support/package-builder/constants.py to "aarch64"
2. sudo make packages

### Expected behavior

Build passes.

### Additional context

<details><summary>"sudo make packages" output:</summary>
<p>

Sanity check for all json files ...
Checking all python code is compilable ...

Creating staging folder and subitems...
Pulling toolchain XRPMS...
Pulling toolchain RPMS...
Generating the install time dependency list for all json files
Could not find spec for createrepo
Step 1: Building the core toolchain packages for x86_64
['filesystem', 'linux-api-headers', 'glibc', 'glibc-libs', 'zlib', 'file', 'binutils', 'gmp', 'mpfr', 'mpc', 'gcc', 'pkg-config', 'ncurses', 'readline', 'bash']

Core toolchain packages are already available

Step 2: Building stage 2 of the toolchain...
['filesystem', 'linux-api-headers', 'glibc', 'glibc-libs', 'zlib', 'file', 'binutils', 'gmp', 'mpfr', 'mpc', 'gcc', 'pkg-config', 'ncurses', 'bash', 'bzip2', 'sed', 'procps-ng', 'coreutils', 'm4', 'grep', 'readline', 'diffutils', 'gawk', 'findutils', 'gettext', 'gzip', 'make', 'patch', 'util-linux', 'attr', 'libacl', 'tar', 'xz', 'libtool', 'flex', 'bison', 'popt', 'nspr', 'sqlite', 'nss', 'elfutils', 'expat', 'libffi', 'libpipeline', 'gdbm', 'perl', 'texinfo', 'autoconf', 'automake', 'openssl-libs', 'zstd', 'rpm', 'dwz', 'debugedit', 'pandoc-bin', 'help2man', 'pcre-libs']

The entire toolchain is now available
---------------------------------------------

Step 3: Building the following package(s) and dependencies...
{'python3-more-itertools', 'python3-iniconfig', 'lldb', 'hiredis', 'ltrace', 'gnupg', 'perl-TermReadKey', 'bzip2', 'python3-lxml', 'python3-setuptools-rust', 'glide', 'gtest', 'libslirp', 'pgbackrest', 'checkpolicy', 'libnetconf2', 'alsa-utils', 'jsoncpp', 'cloud-utils', 'trousers', 'ktap', 'python3-sqlalchemy', 'ant-contrib', 'cpio', 'fail2ban', 'WALinuxAgent', 'nerdctl', 'libXt', 'python3-pyparsing', 'shadow', 'lz4', 'bluez', 'make', 'tpm2-abrmd', 'fakeroot-ng', 'dbus-glib', 'gdbm', 'commons-httpclient', 'ipmitool', 'rubygem-fiber-local', 'rubygem-http-accept', 'perl-IO-Socket-SSL', 'synce4l', 'rubygem-http-cookie', 'python3-netifaces', 'python3-configparser', 'zookeeper', 'finger', 'python3-cffi', 'pam_tacplus', 'python3-jsonpointer', 'copenapi', 'mlocate', 'python3-cryptography', 'libXtst', 'rubygem-msgpack', 'mariadb', 'jq', 'rpm', 'texinfo', 'containers-common', 'libICE', 'network-event-broker', 'conntrack-tools', 'python3-typing-extensions', 'bazel', 'lksctp-tools', 'sbsigntools', 'tinydir', 'python3-resolvelib', 'libXext', 'llvm', 'file', 'passwdqc', 'libteam', 'python3-defusedxml', 'grub2', 'kmod', 'python3-decorator', 'telegraf', 'cups', 'dbus', 'libXrender', 'zchunk', 'openresty', 'i2c-tools', 'dool', 'Linux-PAM', 'psmisc', 'expect', 'cni', 'python3-six', 'yajl', 'monitoring-plugins', 'sudo', 'socat', 'rubygem-trollop', 'apparmor', 'tclap', 'rubygem-serverengine', 'open-sans-fonts', 'coreutils-selinux', 'calico', 'iptables', 'syslinux', 'rubygem-protocol-hpack', 'trace-cmd', 'tar', 'python3-requests', 'python3-docutils', 'perl-libintl', 'python3-gevent', 'lmdb', 'linux-firmware', 'rsync', 'python3-numpy', 'python3-Twisted', 'libffi', 'cyrus-sasl', 'containerd', 'libmnl', 'mpc', 'mm-common', 'policycoreutils', 'xxhash', 'mysql', 'python3-pycparser', 'rubygem-concurrent-ruby', 'libgcrypt', 'p11-kit', 'crun', 'docker-py3', 'minimal', 'jemalloc', 'readline', 'librepo', 'cmocka', 'python3-wrapt', 'perl-Net-SSLeay', 'python3-snowballstemmer', 'rubygem-fluent-plugin-vmware-loginsight', 'strongswan', 'python3-zope.interface', 'itstool', 'less', 'atk', 'crash', 'python3-pyrsistent', 'perl-DBI', 'python3-docopt', 'python3-packaging', 'rubygem-webrick', 'rpcsvc-proto', 'ca-certificates', 'rubygem-zip', 'libical', 'frr', 'doxygen', 'xmlstarlet', 'python3-dateutil', 'termshark', 'haproxy-dataplaneapi', 'xmlto', 'python3-urllib3', 'elfutils', 'nano', 'slang', 'rubygem-mini_portile2', 'sshpass', 'liblogging', 'dejagnu', 'perl-YAML', 'spdlog', 'fuse-overlayfs-snapshotter', 'mesa', 'open-vmdk', 'libatomic_ops', 'netkit-telnet', 'python3-sphinxcontrib-applehelp', 'ivykis', 'iperf', 'gperftools', 'libsemanage', 'geoip-api-c', 'podman', 'spirv-headers', 'python3-jmespath', 'efivar', 'docbook-xml', 'python3-pytest', 'parallel', 'rubygem-bundler', 'bridge-utils', 'rng-tools', 'xerces-c', 'tcp_wrappers', 'rdma-core', 'python3-email-validator', 'docker-pycreds3', 'inotify-tools', 'grpc', 'python3-dnspython', 'capstone', 'freetype2', 'libnetfilter_cttimeout', 'check', 'distrib-compat', 'aide', 'rubygem-public_suffix', 'libnftnl', 'kubernetes-dns', 'python3-ipaddress', 'heapster', 'rubygem-systemd-journal', 'glibmm', 'cassandra', 'zeromq', 'perl-Object-Accessor', 'ibmtpm', 'stig-hardening', 'python3-zope.event', 'shared-mime-info', 'rubygem-async-http', 'unixODBC', 'libgudev', 'python3-asn1crypto', 'acl', 'hyperscan', 'python3-daemon', 'authbind', 'linuxptp', 'procmail', 'python3-distlib', 'tcsh', 'abupdate', 'python3-linux-procfs', 'flannel', 'gcovr', 'libmicrohttpd', 'rpcbind', 'libuv', 'gst-plugins-bad', 'cppunit', 'python3-pathspec', 'traceroute', 'proto', 'go', 'iputils', 'perl-DBD-SQLite', 'python3-pam', 'swig', 'nvme-cli', 'libXScrnSaver', 'python3-pycryptodome', 'samba-client', 'util-macros', 'nicstat', 'fping', 'ipxe', 'cscope', 'procps-ng', 'newt', 'libgpg-error', 'thin-provisioning-tools', 'openjdk11', 'python3-vcversioner', 'pgbouncer', 'autogen', 'ansible', 'cereal', 'dosfstools', 'kafka', 'rootlesskit', 'libtdb', 'python3-webob', 'libksba', 'nss', 'ninja-build', 'libssh2', 'rubygem-fluent-plugin-s3', 'rapidjson', 'kexec-tools', 'aws-sdk-cpp', 'libsolv', 'bubblewrap', 'python3-networkx', 'm4', 'nspr', 'postgresql14', 'ethtool', 'rubygem-mustache', 'libpipeline', 'gpsd', 'mozjs', 'open-isns', 'gpgme', 'photon-os-installer', 'flex', 'rubygem-jmespath', 'python3-py', 'rubygem-unf_ext', 'kube-bench', 'postgresql15', 'rubygem-nokogiri', 'python3-ipaddr', 'libldb', 'libmodulemd', 'python3-virtualenv', 'python3-pyserial', 'python3-autopep8', 'rubygem-remote_syslog_sender', 'perl-Types-Serialiser', 'patch', 'freetds', 'bpftrace', 'erlang-sd_notify', 'gzip', 'pgaudit13', 'shim-signed', 'snoopy', 'fsarchiver', 'paho-c', 'nss-altfiles', 'pandoc-bin', 'rubygem-async-pool', 'bindutils', 'irqbalance', 'python3-pydantic', 'python3-hatch-fancy-pypi-readme', 'inih', 'tpm2-tools', 'python3', 'distcc', 'openldap', 'libXcomposite', 'perl-Parse-Yapp', 'python3-etcd', 'apache-tomcat9', 'network-config-manager', 'drpm', 'xmlsec1', 'python3-sphinxcontrib-htmlhelp', 'lsof', 'gflags', 'chrony', 'perl-NetAddr-IP', 'libxslt', 'debugedit', 'perl-File-Which', 'libusb', 'cdrkit', 'python3-PyNaCl', 'coreutils', 'python3-psutil', 'perl-Data-Validate-IP', 'squid', 'nginx-ingress', 'libsigc++', 'ntp', 'rabbitmq-server', 'python3-pyvim', 'lua', 'json-c', 'http-parser', 'rubygem-protocol-http', 'perftest', 'python3-toml', 'rubygem-rest-client', 'libcap', 'kpatch', 'linux-secure', 'libcgroup', 'rubygem-aws-partitions', 'libsepol', 'libtirpc', 'perl-Exporter-Tiny', 'libdnet', 'python3-coverage', 'protobuf', 'python3-sphinxcontrib-devhelp', 'python3-ecdsa', 'wayland-protocols', 'guile3', 'photon-release', 'python3-oauthlib', 'tzdata', 'libwebp', 'python3-hatchling', 'openipmi', 'help2man', 'toybox', 'fatrace', 'fuse3', 'rubygem-console', 'tboot', 'calico-bgp-daemon', 'python3-mistune', 'dhcp', 'libpwquality', 'python3-alabaster', 'unbound', 'linux', 'pkg-config', 'libunwind', 'rubygem-aws-sdk-sqs', 'nasm', 'rubygem-lru_redux', 'utf8proc', 'grep', 'vim', 'wayland', 'libmbim', 'commons-daemon', 'python3-ply', 'python3-pyudev', 'sysstat', 'lvm2', 'dkms', 'python3-pyinstaller-hooks-contrib', 'python3-configobj', 'mokutil', 'python3-pexpect', 'libbpf', 'falco', 'wavefront-proxy', 'ding-libs', 'libjpeg-turbo', 'rubygem-fluent-plugin-remote_syslog', 'python3-pyvmomi', 'python3-ujson', 'createrepo_c', 'libunistring', 'python3-semantic-version', 'ragel', 'pcre2', 'rubygem-thread_safe', 'backward-cpp', 'rubygem-hpricot', 'python3-fuse', 'perl-Module-Build', 'python3-hypothesis', 'rubygem-optimist', 'ansible-posix', 'libtraceevent', 'python3-lockfile', 'mercurial', 'getdns', 'gobgp', 'rubygem-async-io', 'logrotate', 'ipvsadm', 'subversion', 'ModemManager', 'cracklib', 'numactl', 'lldpad', 'python3-setuptools_scm', 'python3-hyperlink', 'python3-boto', 'xcb-proto', 'sendmail', 'libssh', 'nginx', 'photon-upgrade', 'python3-werkzeug', 'libevent', 'python3-s3transfer', 'python3-psycopg2', 'glib-networking', 'photon-repos', 'double-conversion', 'libtevent', 'libsoup', 'libpcap', 'perl-IPC-Run', 'rubygem-syslog_protocol', 'tpm2-tss', 'python3-pluggy', 'redis', 'libestr', 'python3-nocasedict', 'parted', 'gperf', 'rubygem-tzinfo', 'python3-pkgconfig', 'fuse', 'dwarves', 'gdb', 'python3-botocore', 'python3-pyinstaller', 'open-iscsi', 'librelp', 'python3-simplejson', 'python3-service_identity', 'rubygem-sigdump', 'pigz', 'rubygem-traces', 'rubygem-yajl-ruby', 'lshw', 'rubygem-rdiscount', 'dos2unix', 'python3-ConcurrentLogHandler', 'pciutils', 'rust', 'gettext', 'libtalloc', 'ed', 'rubygem-fluent-plugin-kubernetes_metadata_filter', 'vulkan-headers', 'blktrace', 'wget', 's3fs-fuse', 'autofs', 'guile', 'rubygem-unf', 'hyper-v', 'device-mapper-multipath', 'dbus-broker', 'qemu-img', 'cifs-utils', 'lttng-tools', 'python3-msgpack', 'polkit', 'conmon', 'libXcursor', 'xml-security-c', 'cloud-init', 'password-store', 'python3-Pygments', 'rrdtool', 'python3-jinja2', 'libtracefs', 'ebtables', 'leveldb', 'selinux-policy', 'rubygem-mini_portile', 'rubygem-llhttp-ffi', 'perl-Path-Class', 'meson', 'intltool', 'kubernetes-metrics-server', 'runit', 'watchdog', 'kapacitor', 'fuse-overlayfs', 'python3-babel', 'python3-flit-core', 'rubygem-unicode-display_width', 'which', 'apache-tomcat10', 'aufs-util', 'chrpath', 'krb5', 'pgaudit15', 'serf', 'libarchive', 'raspberrypi-firmware', 'python3-deepmerge', 'python3-nocaselist', 'iniparser', 'rubygem-libxml-ruby', 'emacs', 'rt-tests', 'bcc', 'postgresql10', 'attr', 'iotop', 'python3-systemd', 'httpd-mod_jk', 'oniguruma', 'systemd', 'curl', 'libxshmfence', 'libnl', 'squashfs-tools', 'libpsl', 'python3-cassandra-driver', 'openscap', 'libgd', 'perl-Canary-Stability', 'python3-mako', 'gstreamer', 'vulkan-tools', 'lzo', 'strace', 'python3-filelock', 'harfbuzz', 'fribidi', 'perl-Crypt-SSLeay', 'python3-ndg-httpsclient', 'cronie', 'libXrandr', 'cppcheck', 'python3-yamlloader', 'rubygem-builder', 'rubygem-oj', 'cython3', 'syslog-ng', 'python3-graphviz', 'uwsgi', 'tuned', 'netcat', 'gawk', 'postgresql13', 'dbxtool', 'apache-maven', 'dbus-python3', 'libnetfilter_cthelper', 'google-benchmark', 'dmidecode', 'python3-M2Crypto', 'rubygem-mime-types', 'gnu-efi', 'vulkan-loader', 'atftp', 'rubygem-timers', 'cmake', 'rubygem-strptime', 'librsync', 'elixir', 'haveged', 'rubygem-http_parser.rb', 'libtiff', 'libcbor', 'python3-constantly', 'coredns', 'openvswitch', 'icu', 'libXdamage', 'tinycdb', 'python3-sphinx', 'python3-pika', 'python3-pycryptodomex', 'python3-markupsafe', 'hdparm', 'haproxy', 'python3-schedutils', 'nss-pam-ldapd', 'perl-Module-ScanDeps', 'python3-pyasn1', 'git-lfs', 'python3-tzlocal', 'python3-backports.ssl_match_hostname', 'apache-tomcat-native', 'libpng', 'perl-URI', 'ruby', 'python3-prompt_toolkit', 'libepoxy', 'powershell', 'zsh', 'gdk-pixbuf', 'pango', 'openssh', 'ndctl', 'perl-YAML-Tiny', 'python3-ntplib', 'nettle', 'lttng-ust', 'kbd', 'libedit', 'rubygem-nio4r', 'btrfs-progs', 'python3-importlib-metadata', 'gnome-common', 'python3-pytz-deprecation-shim', 'man-pages', 'libnetfilter_conntrack', 'gtk3', 'gssntlmssp', 'libXinerama', 'python3-boto3', 'unzip', 'libtasn1', 'apr', 'tdnf', 'clang', 'rubygem-aws-sdk-core', 'nodejs', 'python3-netaddr', 'cloud-network-setup', 'ctags', 'python3-wheel', 'rubygem-aws-eventstream', 'dialog', 'grub2-theme', 'chkconfig', 'usbutils', 'libXfont2', 'libassuan', 'perl-JSON', 'hwloc', 'python3-PyYAML', 'rubygem-netrc', 'lapack', 'python3-pytz', 'sssd', 'libX11', 'python3-binary', 'mpfr', 'libqmi', 'ddclient', 'python3-pyjsparser', 'python3-sphinxcontrib-jsmath', 'libecap', 'xorriso', 'asciidoc3', 'gcc', 'rubygem-http', 'libSM', 'rubygem-domain_name', 'rubygem-http-form_data', 'json-glib', 'rubygem-i18n', 'zlib', 'libaio', 'ipcalc', 'rubygem-addressable', 'rubygem-aws-sdk-s3', 'python3-pyflakes', 'setools', 'rpm-ostree', 'gmp', 'font-util', 'dotnet-sdk', 'pinentry', 'virt-what', 'alsa-lib', 'python3-ruamel-yaml', 'python3-altgraph', 'rubygem-activesupport', 'pycurl3', 'python3-appdirs', 'keyutils', 'rubygem-aws-sdk-kms', 'etcd', 'yaml-cpp', 'perl-Config-IniFiles', 'libnsl', 'colm', 'libglvnd', 'python3-paramiko', 'tpm2-pkcs11', 'libxkbcommon', 'python3-CacheControl', 'apache-ant', 'pth', 'python3-pyroute2', 'bison', 'xtrans', 'at-spi2-core', 'libsodium', 'python3-pywbem', 'dotnet-runtime', 'python3-ethtool', 'python3-geomet', 'repmgr14', 'libpciaccess', 'python3-typing', 'calico-bird', 'pcre', 'byacc', 'libtar', 'cri-tools', 'python3-platformdirs', 'semodule-utils', 'log4cpp', 'memcached', 'repmgr13', 'rubygem-dig_rb', 'bc', 'net-tools', 'msr-tools', 'libseccomp', 'python3-websocket-client', 'protobuf-c', 'python3-requests-unixsocket', 'groff', 'python3-terminaltables', 'python3-cqlsh', 'python3-ptyprocess', 'vernemq', 'git', 'photon-iso-config', 'lasso', 'rubygem-terminal-table', 'rubygem-tzinfo-data', 'lxcfs', 'dnsmasq', 'bats', 'glslang', 'python3-pycodestyle', 'xorg-fonts', 'shim', 'influxdb', 'python3-tornado', 'libXi', 'python3-bcrypt', 'gc', 'fontconfig', 'stalld', 'rubygem-fluent-plugin-systemd', 'libcap-ng', 'rsyslog', 'perl-File-HomeDir', 'runc', 'motd', 'rubygem-rbvmomi', 'mkinitcpio', 'iproute2', 'cpulimit', 'pgaudit14', 'python3-imagesize', 'go-md2man', 'python3-idna', 'autoconf-archive', 'expat', 'tmux', 'tpm2-pytss', 'sed', 'libXau', 'GConf', 'net-snmp', 'libxcb', 'python3-pygobject', 'libselinux', 'rubygem-protocol-http2', 'python3-chardet', 'perl', 'libdaemon', 'wpa_supplicant', 'rubygem-async', 'binutils', 'eventlog', 'argon2', 'python3-hatch-vcs', 'perl-WWW-Curl', 'efibootmgr', 'rubygem-ffi-compiler', 'libfido2', 'consul', 'python3-click', 'sg3_utils', 'pcstat', 'python3-Js2Py', 'npth', 'python3-pyOpenSSL', 'python3-PyJWT', 'photon-os-container-builder', 'spirv-tools', 'keepalived', 'dwz', 'xfsprogs', 'rubygem-http-parser', 'popt', 'xz', 'perl-DBIx-Simple', 'glibc', 'filesystem', 'abseil-cpp', 'kubernetes-dashboard', 'lsscsi', 'libconfig', 'openjdk17', 'mc', 'htop', 'rubygem-multi_json', 'initscripts', 'gtk-doc', 'dtc', 'libdrm', 'vsftpd', 'duktape', 'systemtap', 'jna', 'libnfnetlink', 'python3-mock', 'tree', 'perl-JSON-Any', 'libnetfilter_queue', 'nfs-utils', 'ostree', 'perl-common-sense', 'xorg-applications', 'cairo', 'python3-charset-normalizer', 'python3-jsonschema', 'libyaml', 'bluez-tools', 'docbook-xsl', 'perl-JSON-XS', 'docker', 'mingetty', 'libxml2', 'XML-Parser', 'tcpdump', 'python3-pbr', 'ntpsec', 'perl-Try-Tiny', 'nghttp2', 'ipset', 'rubygem-kubeclient', 'gobject-introspection', 'python3-automat', 'libtool', 'glog', 'wireshark', 'cryptsetup', 'rubygem-protocol-http1', 'amdvlk', 'automake', 'libndp', 'autoconf', 'libfastjson', 'libmspack', 'gptfdisk', 'python3-xmltodict', 'findutils', 'python3-prettytable', 'geos', 'perl-Module-Install', 'graphene', 'rubygem-jsonpath', 'rubygem-mime-types-data', 'repmgr15', 'rubygem-cool-io', 'sysdig', 'calico-libnetwork', 'zstd', 'diffutils', 'python3-PyHamcrest', 'wireguard-tools', 'govmomi', 'linux-esx', 'python3-pyasn1-modules', 'rubygem-backports', 'initramfs', 'sqlite', 'bash', 'perl-CGI', 'nmap', 'httpd', 'python3-distro', 'python3-wcwidth', 'rubygem-fluent-plugin-concat', 'zip', 'linux-rt', 'python3-greenlet', 'userspace-rcu', 'python3-prometheus_client', 'python3-requests-toolbelt', 'rubygem-fluentd', 'glib', 'linux-api-headers', 'lm-sensors', 'python3-jsonpatch', 're2', 'perl-List-MoreUtils', 'pmd-ng', 'rubygem-ronn', 'jc', 'whois', 'rubygem-ffi', 'gnutls', 'ImageMagick', 'kubernetes', 'edgex', 'python3-scp', 'gstreamer-plugins-base', 'python3-certifi', 'python3-sphinxcontrib-qthelp', 'rubygem-io-event', 'python3-argparse', 'perl-Perl4-CoreLibs', 'scons', 'dracut', 'cve-check-tool', 'selinux-python', 'libXfixes', 'build-essential', 'docker-compose', 'rubygem-aws-sigv4', 'man-db', 'suricata', 'openssl', 'util-linux', 'librdkafka', 'fio', 'python3-sphinxcontrib-serializinghtml', 'ncurses', 'python3-sortedcontainers', 'tcl', 'libvirt', 'python3-atomicwrites', 'apr-util', 'python3-incremental', 'iptraf-ng', 'libev', 'libyang', 'c-ares', 'gnuplot', 'iana-etc', 'valgrind', 'pixman', 'google-compute-engine', 'jansson', 'tuna', 'boost', 'libfontenc', 'rubygem-highline', 'audit', 'slirp4netns', 'python3-attrs', 'python3-iniparse', 'libhugetlbfs', 'e2fsprogs', 'open-vm-tools', 'python3-zmq', 'ansible-community-general', 'rubygem-recursive-open-struct', 'dejavu-fonts', 'libnvme', 'snappy', 'xinetd', 'libgssglue', 'libXdmcp', 'erlang', 'nftables'}

Package build has been completed

Step 1: Building the core toolchain packages for aarch64
['filesystem', 'linux-api-headers', 'glibc', 'glibc-libs', 'zlib', 'file', 'binutils', 'gmp', 'mpfr', 'mpc', 'gcc', 'pkg-config', 'ncurses', 'readline', 'bash']

The following core toolchain packages need to be built: 
['filesystem', 'glibc', 'glibc-libs', 'zlib', 'file', 'binutils', 'gmp', 'mpfr', 'mpc', 'gcc', 'pkg-config', 'ncurses', 'readline', 'bash']
Package Status: Total: 15 Building: 1 Broken: 0 Pending: 13 Done: 1
Failed while building package: filesystem
tail: cannot open '/home/ubuntu/git/photon/stage/LOGS/filesystem-1.1.aarch64/filesystem.log' for reading: No such file or directory

filesystem-1.1.x86_64 not found in available packages
Traceback (most recent call last):
  File "/home/ubuntu/git/photon/support/package-builder/PackageBuilder.py", line 45, in build
    self._buildPackage()
  File "/home/ubuntu/git/photon/support/package-builder/PackageBuilder.py", line 81, in _buildPackage
    raise e
  File "/home/ubuntu/git/photon/support/package-builder/PackageBuilder.py", line 59, in _buildPackage
    tUtils.installToolchainRPMS(self.sandbox, self.package, self.version, availablePackages=self.doneList)
  File "/home/ubuntu/git/photon/support/package-builder/ToolChainUtils.py", line 128, in installToolchainRPMS
    raise Exception("%s-%s.%s not found in available packages" % (package, version, constants.buildArch))
Exception: filesystem-1.1.x86_64 not found in available packages
filesystem-1.1.x86_64 not found in available packages
Traceback (most recent call last):
  File "/home/ubuntu/git/photon/support/package-builder/WorkerThread.py", line 29, in run
    pkgBuilder.build(pkg, doneList)
  File "/home/ubuntu/git/photon/support/package-builder/PackageBuilder.py", line 49, in build
    raise e
  File "/home/ubuntu/git/photon/support/package-builder/PackageBuilder.py", line 45, in build
    self._buildPackage()
  File "/home/ubuntu/git/photon/support/package-builder/PackageBuilder.py", line 81, in _buildPackage
    raise e
  File "/home/ubuntu/git/photon/support/package-builder/PackageBuilder.py", line 59, in _buildPackage
    tUtils.installToolchainRPMS(self.sandbox, self.package, self.version, availablePackages=self.doneList)
  File "/home/ubuntu/git/photon/support/package-builder/ToolChainUtils.py", line 128, in installToolchainRPMS
    raise Exception("%s-%s.%s not found in available packages" % (package, version, constants.buildArch))
Exception: filesystem-1.1.x86_64 not found in available packages
Package Status: Total: 15 Building: 0 Broken: 1 Pending: 13 Done: 1
Some of the packages failed:
['filesystem-1.1']
Failed during building package
Traceback (most recent call last):
  File "/home/ubuntu/git/photon/build.py", line 1609, in main
    attr()
  File "/home/ubuntu/git/photon/build.py", line 704, in packages
    Builder.buildPackagesForAllSpecs(
  File "/home/ubuntu/git/photon/support/package-builder/builder.py", line 60, in buildPackagesForAllSpecs
    Builder.buildSpecifiedPackages(listPackages, buildThreads, pkgBuildType, pkgInfoJsonFile, logger)
  File "/home/ubuntu/git/photon/support/package-builder/builder.py", line 36, in buildSpecifiedPackages
    pkgManager.buildPackages(listPackages, buildThreads)
  File "/home/ubuntu/git/photon/support/package-builder/PackageManager.py", line 107, in buildPackages
    self.buildToolChainPackages(buildThreads)
  File "/home/ubuntu/git/photon/support/package-builder/PackageManager.py", line 77, in buildToolChainPackages
    pkgCount = self.buildToolChain()
  File "/home/ubuntu/git/photon/support/package-builder/PackageManager.py", line 70, in buildToolChain
    self._buildPackages(1)
  File "/home/ubuntu/git/photon/support/package-builder/PackageManager.py", line 241, in _buildPackages
    raise Exception("Failed during building package")
Exception: Failed during building package
make: *** [Makefile:6: packages] Error 1

</p>
</details>

**Comment by oliverkurth** [comment]
Cross compiling isn't supported for Photon OS builds, we build natively for different architectures. You can try `qemu`, or use docker containers with the `--platform` argument, but that will be very slow.

**Comment by rousku** [comment]
Is the support for cross compiling in the roadmap? I can see from the code that there have been efforts to implement it.

**Comment by YustasSwamp** [comment]
Cross compilation was supported at some point. But we decided to use native aarch64 compilation instead. So, this core was not kept up to date since then. No plans on our roadmap to reshape it.

**Comment by dcasota** [comment]
@rousku From a history view, Photon OS never had docs chapters about their cross-aarch64-tools and
- how to set up a cross-compiler
- recommended compiler versions
- cross-debugger, etc.

At that "Dell era", the Emulex-style of software toolings for network adapters, storage hbas, wasn't a topic for cloud-native goals.

Have a look to [photon-xc-aarch64 Dockerfile](https://raw.githubusercontent.com/vmware/photon/100c55b180016e83e977990f75b049185b448cb8/support/cross/docker/toolchain/photon-xc-aarch64/Dockerfile), you can see that the Photon OS team maintained that sort of Antikythera, indeed!

Tinkering with rebuilding the cross-compiler feature, I failed  using the fedora bits of gcc-aarch64-linux-gnu, see [here](https://github.com/vmware/photon/files/13997575/attempt.build.cross-compiler.tools.txt). Yes I've added all aarch64 repos from https://packages.vmware.com/photon/5.0 to `/etc/yum.repos.d`. But there were too many conflicts with prerequisites when starting `make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu packages-minimal`.
