### ISSUE TITLE
check_spec_files fails

### ISSUE THREAD

**Issue by rousku** [vmware/photon#1534]
### Describe the bug

I'm trying to build packages, bu the check_spec_files step fails.

### Reproduction steps

1. git checkout 550a466822b07eaa0b11c
2. sudo make packages-minimal

### Expected behavior

Build passes

### Additional context

Sanity check for all json files ...
Checking all python code is compilable ...

Creating staging folder and subitems...
Pulling toolchain XRPMS...
Pulling toolchain RPMS...
Checking spec file: SPECS/linux/linux-rt-drivers-intel-ice-1.9.11.spec

Some mentioned but unused files found in the spec.
If you think it's a false positive, try the following methods:
- If you are using Photon OS, update rpm version to latest using tdnf and retry
- If you are using any other distro, contact - 'sshedi@vmware.com'

--- List of errors in SPECS/linux/linux-rt-drivers-intel-ice-1.9.11.spec ---

 --- List of unused files ---
List of unused files in: SPECS/linux
ice-1.9.11.tar.gz

Spec file check failed
Traceback (most recent call last):
  File "/data/git/photon/build.py", line 1593, in main
    attr = getattr(RpmBuildTarget(), configdict["targetName"])
  File "/data/git/photon/build.py", line 634, in __init__
    CheckTools.check_spec_files()
  File "/data/git/photon/build.py", line 985, in check_spec_files
    raise Exception("Spec file check failed")
Exception: Spec file check failed
make: *** [Makefile:6: packages-minimal] Error 1

**Comment by sshedi** [comment]
What's the version of `rpm` you are using in your build host?
pastee the output of `rpm -q rpm`

**Comment by rousku** [comment]
I'm building on ubuntu.

```
azureuser@armbuild:/data/git/photon$ rpm --version
RPM version 4.17.0
```
