### ISSUE TITLE
vmhgfs

### ISSUE THREAD

**Issue by nnordrum** [vmware/photon#226]
I feel like I'm missing something here... I can't seem to mount a directory from Windows through VMware Player into Photon. [open-vm-tools.spec] (https://github.com/vmware/photon/blob/fc7b4b686b46cc5bc4d0e63f78c619ced4e334fa/SPECS/open-vm-tools/open-vm-tools.spec) certainly seems to imply that it should be doable.

Here's what I did:
* create a vm with a share called "test"
* minimal photon install
* systemctl enable vmtoolsd
* systemctl start vmtoolsd
* mkdir /mnt/test
* vmware-hgfsclient
  * show the share I have configured in VMware Player
* /usr/sbin/mount.vmhgfs .host:/ /mnt/test
  * Error: cannot mount filesystem: No such device
* /usr/sbin/mount.vmhgfs .host:/ /mnt/test-directory-does-not-exist
  * Error: cannot canonicalize mount point: No such file or directory
* /usr/sbin/mount.vmhgfs -v .host:/ /mnt/test
  * Original command line: "/usr/sbin/mount.vmhgfs -v .host:/ /mnt/test"
  * Host component of share name is ".host"
  * Directory component of share name is "/"
  * Error: cannot mount filesystem: No such device

It seems like all the components are there, but it's just missing some magic glue...

**Comment by suezzelur** [comment]
What happens when you specifically mount a share location like below:

mount -t vmhgfs .host:/foo /mnt/foo
or add an entry to /etc/fstab file?
https://pubs.vmware.com/workstation-9/index.jsp?topic=%2Fcom.vmware.ws.using.doc%2FGUID-AB5C80FE-9B8A-4899-8186-3DB8201B1758.html

**Comment by suezzelur** [comment]
Also, are you using a TP1 build of photon? vmhgfs was added as a kernel module in a later build (current master build has this inbuilt). Can you do lsmod | grep vmhgfs and see if the module is running?

**Comment by nnordrum** [comment]
* mount -t vmhgfs .host:/foo /mnt/foo
  * mount: unknown filesystem type 'vmhgfs'

if I do:
* ln -s /usr/sbin/mount.vmhgfs /sbin/mount.vmhgfs
then:
* mount -t vmhgfs .host:/foo /mnt/foo
  * Error: cannot mount filesystem: No such device

* cat /etc/photon-release
  * VMware Photon Linux 1.0 TP1

no out put for "lsmod | grep vmhgfs"

I'm grabbing photon-1.0.0-195.iso right now, but feeling good about this newer build. I'll update.

**Comment by nnordrum** [comment]
I see identical behavior with 1.0.0-195 Minimal install.

**Comment by suezzelur** [comment]
195 build unfortunately does not have the kernel component. Are you able to build photon from github using make iso?

**Comment by toliaqat** [comment]
We will upload a new build soon with vmhgfs support in it. Will update here as soon as it is available for download.

**Comment by nnordrum** [comment]
Sounds great--look forward to it! Thanks.

**Comment by nnordrum** [comment]
Tried building from git, but can't seem to get it to work.

In an effort to make it as reproducible as possible, here's a Dockerfile:
```
FROM ubuntu

RUN apt-get update
RUN apt-get -y install bison gawk g++ createrepo python-aptdaemon genisoimage texinfo python-requests git wget unzip
RUN ln -sf /bin/bash /bin/sh
RUN git clone https://github.com/vmware/photon.git
WORKDIR /photon/
RUN mkdir -p /photon/stage/SOURCES
RUN make minimal
```

I get stuck at the same place using this Dockerfile as when I tried it in Ubuntu 14.04 workstation running in VMware.

```
2015-08-13 18:40:38,682 - PackageManager - INFO - --------------------------------------------------------------------------
2015-08-13 18:40:38,682 - PackageManager - INFO - Staring Log
2015-08-13 18:40:38,682 - PackageManager - INFO - --------------------------------------------------------------------------
2015-08-13 18:40:38,682 - Toolchain Utils - INFO - --------------------------------------------------------------------------
2015-08-13 18:40:38,682 - Toolchain Utils - INFO - Staring Log
2015-08-13 18:40:38,682 - Toolchain Utils - INFO - --------------------------------------------------------------------------
2015-08-13 18:40:38,682 - Toolchain Utils - INFO - Building core tool chain packages.....
2015-08-13 18:40:38,693 - Toolchain Utils - INFO - Preparing build environment
2015-08-13 18:40:39,112 - Toolchain Utils - ERROR - Prepare build root script failed.Unable to prepare chroot.
2015-08-13 18:40:39,112 - Toolchain Utils - ERROR - Unable to build tool chain.
Traceback (most recent call last):
  File "/photon/support/package-builder/ToolChainUtils.py", line 144, in buildCoreToolChainPackages
    self.installToolChainRPMS(chrootID)
  File "/photon/support/package-builder/ToolChainUtils.py", line 160, in installToolChainRPMS
    self.prepareBuildRoot(chrootID)
  File "/photon/support/package-builder/ToolChainUtils.py", line 39, in prepareBuildRoot
    raise Exception("Prepare build root script failed")
Exception: Prepare build root script failed
2015-08-13 18:40:39,113 - PackageManager - ERROR - Unable to build tool chain
2015-08-13 18:40:39,113 - PackageManager - ERROR - Prepare build root script failed
2015-08-13 18:40:39,113 - /photon/stage/LOGS/Main - ERROR - Caught an exception
2015-08-13 18:40:39,113 - /photon/stage/LOGS/Main - ERROR - Prepare build root script failed
Traceback (most recent call last):
  File "/photon/support/package-builder/builder.py", line 121, in main
    buildPackagesFromGivenJSONFile(options.inputJSONFile, options.buildOption,logger, options.buildThreads)
  File "/photon/support/package-builder/builder.py", line 175, in buildPackagesFromGivenJSONFile
    pkgManager.buildPackages(listPackagesToBuild, buildThreads)
  File "/photon/support/package-builder/PackageManager.py", line 105, in buildPackages
    self.buildToolChainPackages(buildThreads)
  File "/photon/support/package-builder/PackageManager.py", line 101, in buildToolChainPackages
    self.buildToolChain()
  File "/photon/support/package-builder/PackageManager.py", line 98, in buildToolChain
    raise e
Exception: Prepare build root script failed
make: *** [packages-minimal] Error 1
INFO[0028] The command [/bin/sh -c make minimal] returned a non-zero code: 2
```

In the least naggy way possible, any ballpark idea when the next build will get released? or how to work around this build issue?

**Comment by suezzelur** [comment]
You can now use the latest uploaded iso from bintray
https://bintray.com/vmware/photon/iso/latest/view#files
The build has vmhgfs built in the kernel.

**Comment by nnordrum** [comment]
just noticed that while trying to clone the dev branch :)

works for me now--thanks!
