### ISSUE TITLE
Package createrepo has missing dependency of deltarpm

### ISSUE THREAD

**Issue by toliaqat** [vmware/photon#23]
Createrepo is throwing following error in Photon
```
root [ /workspace/photon ]# createrepo
Traceback (most recent call last):
  File "/usr/share/createrepo/genpkgmetadata.py", line 29, in <module>
    import createrepo
  File "/usr/lib/python2.7/site-packages/createrepo/__init__.py", line 53, in <module>
    import deltarpms
  File "/usr/lib/python2.7/site-packages/createrepo/deltarpms.py", line 21, in <module>
    import deltarpm
ImportError: No module named deltarpm
```

**Comment by WongBynn** [comment]
yum install python*
