### ISSUE TITLE
broken build

### ISSUE THREAD

**Issue by sofar** [vmware/photon#379]
new ubuntu-14 server x86 install, followed build-photon.md and build breaks early on:

commit e3b980c13d1ed93665724cefb7c3f417f8d63e5c

```
2015-10-01 08:15:12,070 - Serializable Spec objects - INFO - --------------------------------------------------------------------------
2015-10-01 08:15:12,070 - Serializable Spec objects - INFO - Staring Log
2015-10-01 08:15:12,070 - Serializable Spec objects - INFO - --------------------------------------------------------------------------
2015-10-01 08:15:12,425 - PackageManager - INFO - --------------------------------------------------------------------------
2015-10-01 08:15:12,427 - PackageManager - INFO - Staring Log
2015-10-01 08:15:12,427 - PackageManager - INFO - --------------------------------------------------------------------------
2015-10-01 08:15:12,427 - Toolchain Utils - INFO - --------------------------------------------------------------------------
2015-10-01 08:15:12,427 - Toolchain Utils - INFO - Staring Log
2015-10-01 08:15:12,427 - Toolchain Utils - INFO - --------------------------------------------------------------------------
2015-10-01 08:15:12,427 - Toolchain Utils - INFO - Building core tool chain packages.....
2015-10-01 08:15:12,438 - Toolchain Utils - INFO - Successfully destroyed chroot:/home/ahkok/photon/stage/photonroot/build-core-toolchain
2015-10-01 08:15:12,440 - Toolchain Utils - INFO - Preparing build environment
2015-10-01 08:15:12,460 - Toolchain Utils - DEBUG - Installing filesystem rpms:filesystem
rpm: RPM should not be used directly install RPM packages, use Alien instead!
rpm: However assuming you know what you are doing...
warning: group utmp does not exist - using root
2015-10-01 08:15:12,614 - Toolchain Utils - INFO - Successfully prepared chroot:/home/ahkok/photon/stage/photonroot/build-core-toolchain
2015-10-01 08:15:12,614 - Toolchain Utils - INFO - Installing Tool Chain RPMS.......
2015-10-01 08:15:12,944 - Toolchain Utils - DEBUG - Installing rpms: linux-api-headers glibc glibc-devel zlib zlib-devel file binutils binutils-devel gmp gmp-devel mpfr mpfr-devel mpc libgcc libgcc-devel libstdc++ libstdc++-devel libgomp libgomp-devel gcc pkg-config ncurses bash bzip2 sed ncurses-devel procps-ng coreutils m4 grep readline diffutils gawk findutils gettext gzip make patch util-linux tar xz libtool flex bison readline-devel lua lua-devel popt popt-devel nspr sqlite-autoconf nss nss-devel bzip2-devel elfutils-libelf elfutils elfutils-libelf-devel elfutils-devel expat libffi libpipeline gdbm perl texinfo autoconf automake openssl openssl-devel python2 python2-libs python2-devel rpm rpm-build rpm-devel groff man-db man-pages cpio
rpm: RPM should not be used directly install RPM packages, use Alien instead!
rpm: However assuming you know what you are doing...
warning: /home/ahkok/photon/stage/PUBLISHRPMS/noarch/linux-api-headers-4.0.9-1.ph1tp2.noarch.rpm: Header V3 RSA/SHA1 Signature, key ID 66fd4949: NOKEY
warning: %post(bash-4.3-4.ph1tp2.x86_64) scriptlet failed, exit status 127
error: unpacking of archive failed on file /sbin/ldconfig;560d4e01: cpio: read failed - No such file or directory
error: glibc-2.21-5.ph1tp2.x86_64: install failed
warning: %post(ncurses-5.9-2.ph1tp2.x86_64) scriptlet failed, exit status 127
warning: %post(readline-6.3-3.ph1tp2.x86_64) scriptlet failed, exit status 127
warning: %post(zlib-1.2.8-2.ph1tp2.x86_64) scriptlet failed, exit status 127
warning: %post(gmp-5.1.3-1.ph1tp2.x86_64) scriptlet failed, exit status 127
warning: %post(elfutils-libelf-0.158-3.ph1tp2.x86_64) scriptlet failed, exit status 127
warning: %post(mpfr-3.1.2-1.ph1tp2.x86_64) scriptlet failed, exit status 127
warning: %post(lua-5.2.3-1.ph1tp2.x86_64) scriptlet failed, exit status 127
warning: %post(bzip2-1.0.6-3.ph1tp2.x86_64) scriptlet failed, exit status 127
warning: %post(popt-1.16-1.ph1tp2.x86_64) scriptlet failed, exit status 127
warning: %post(file-5.22-1.ph1tp2.x86_64) scriptlet failed, exit status 127
warning: %post(gdbm-1.11-1.ph1tp2.x86_64) scriptlet failed, exit status 127
warning: %post(perl-5.18.2-2.ph1tp2.x86_64) scriptlet failed, exit status 127
warning: %post(openssl-1.0.2d-2.ph1tp2.x86_64) scriptlet failed, exit status 127
warning: %post(python2-2.7.9-3.ph1tp2.x86_64) scriptlet failed, exit status 127
warning: %post(flex-2.5.38-2.ph1tp2.x86_64) scriptlet failed, exit status 127
warning: %post(coreutils-8.22-1.ph1tp2.x86_64) scriptlet failed, exit status 127
warning: %post(nspr-4.10.8-1.ph1tp2.x86_64) scriptlet failed, exit status 127
warning: %post(sqlite-autoconf-3080301-1.ph1tp2.x86_64) scriptlet failed, exit status 127
warning: %post(nss-3.19-2.ph1tp2.x86_64) scriptlet failed, exit status 127
warning: %post(rpm-4.11.2-6.ph1tp2.x86_64) scriptlet failed, exit status 127
warning: %post(binutils-2.25-1.ph1tp2.x86_64) scriptlet failed, exit status 127
warning: %post(elfutils-0.158-3.ph1tp2.x86_64) scriptlet failed, exit status 127
warning: %post(mpc-1.0.2-1.ph1tp2.x86_64) scriptlet failed, exit status 127
error: unpacking of archive failed on file /usr/include/c++/4.8.2/ext/pb_ds/detail/binary_heap_/entry_cmp.hpp;560d4e01: cpio: read failed - No such file or directory
error: libstdc++-devel-4.8.2-4.ph1tp2.x86_64: install failed
warning: %post(expat-2.1.0-1.ph1tp2.x86_64) scriptlet failed, exit status 127
warning: %post(libffi-3.1-1.ph1tp2.x86_64) scriptlet failed, exit status 127
warning: %post(libpipeline-1.2.6-1.ph1tp2.x86_64) scriptlet failed, exit status 127
error: unpacking of archive failed on file /usr/bin/grotty;560d4e01: cpio: read failed - No such file or directory
error: groff-1.22.2-1.ph1tp2.x86_64: install failed
warning: %post(xz-5.0.5-2.ph1tp2.x86_64) scriptlet failed, exit status 127
error: unpacking of archive failed on file /usr/lib64/libmudflap.so.0.0.0;560d4e01: cpio: read failed - No such file or directory
error: gcc-4.8.2-4.ph1tp2.x86_64: install failed
warning: %post(man-db-2.6.6-1.ph1tp2.x86_64) scriptlet failed, exit status 127
error: unpacking of archive failed on file /usr/lib/libgettextlib-0.18.3.so;560d4e01: cpio: read failed - No such file or directory
error: gettext-0.18.3.2-1.ph1tp2.x86_64: install failed
warning: %post(gawk-4.1.0-2.ph1tp2.x86_64) scriptlet failed, exit status 127
warning: %post(util-linux-2.24.1-2.ph1tp2.x86_64) scriptlet failed, exit status 127
warning: %post(procps-ng-3.3.9-2.ph1tp2.x86_64) scriptlet failed, exit status 127
warning: %post(findutils-4.4.2-1.ph1tp2.x86_64) scriptlet failed, exit status 127
warning: %post(libtool-2.4.2-1.ph1tp2.x86_64) scriptlet failed, exit status 127
2015-10-01 08:15:22,016 - Toolchain Utils - ERROR - Installing tool chain  failed
2015-10-01 08:15:22,016 - Toolchain Utils - ERROR - Unable to build tool chain.
Traceback (most recent call last):
  File "/home/ahkok/photon/support/package-builder/ToolChainUtils.py", line 175, in buildCoreToolChainPackages
    self.installToolChainRPMS(chrootID)
  File "/home/ahkok/photon/support/package-builder/ToolChainUtils.py", line 212, in installToolChainRPMS
    raise "RPM installation failed"
TypeError: exceptions must be old-style classes or derived from BaseException, not str
2015-10-01 08:15:22,017 - PackageManager - ERROR - Unable to build tool chain
2015-10-01 08:15:22,017 - PackageManager - ERROR - exceptions must be old-style classes or derived from BaseException, not str
2015-10-01 08:15:22,017 - /home/ahkok/photon/stage/LOGS/Main - ERROR - Caught an exception
2015-10-01 08:15:22,017 - /home/ahkok/photon/stage/LOGS/Main - ERROR - exceptions must be old-style classes or derived from BaseException, not str
Traceback (most recent call last):
  File "/home/ahkok/photon/support/package-builder/builder.py", line 128, in main
    buildAPackage(package, options.buildThreads)
  File "/home/ahkok/photon/support/package-builder/builder.py", line 215, in buildAPackage
    pkgManager.buildPackages(listPackages, buildThreads)
  File "/home/ahkok/photon/support/package-builder/PackageManager.py", line 101, in buildPackages
    self.buildToolChainPackages(buildThreads)
  File "/home/ahkok/photon/support/package-builder/PackageManager.py", line 97, in buildToolChainPackages
    self.buildToolChain()
  File "/home/ahkok/photon/support/package-builder/PackageManager.py", line 94, in buildToolChain
    raise e
TypeError: exceptions must be old-style classes or derived from BaseException, not str
make: *** [iso-minimal] Error 1
```

**Comment by sharathjg** [comment]
What version of python do you have?

**Comment by jobinar** [comment]
Facing the same issue with python version 2.7.6

**Comment by sofar** [comment]
Stock ubuntu server 14.04 x86_64, Python version 2.7.6

Issue cause: Malformed RPM downloads cause RPM install to fail, which triggers the -wrongly-implemented- exception

```Raise "string...."```

should be

``` raise Exception("string....")```

so this would fix it:

```
diff --git a/support/package-builder/ToolChainUtils.py b/support/package-builder/ToolChainUtils.py
index 1e6b5c8..025a84d 100644
--- a/support/package-builder/ToolChainUtils.py
+++ b/support/package-builder/ToolChainUtils.py
@@ -209,7 +209,7 @@ class ToolChainUtils(object):
         retval = process.wait()
         if retval != 0:
             self.logger.error("Installing tool chain  failed")
-            raise "RPM installation failed"
+            raise Exception("RPM installation failed")
             
         self.logger.info("Successfully installed all Tool Chain RPMS in Chroot:"+chrootID)    
     
```

ROOT CAUSE:

it seems downloads are not verified and railed RPM downloads cause this issue. After blowing away the broken downloads and retrying, it works.

An obvious fix (apart from the syntax fix in the exception) would be to do error checking after the download thread finishes, and catch that the download did not succeed properly.

**Comment by moseslg** [comment]
I see a similar issue in my build and it fails. I see the below error keep showing up repeatedly in the build logs. Tried this on 2 Ubuntu VMs and had the same issue.

> it seems downloads are not verified and failed RPM downloads cause this issue.After blowing away the broken downloads and retrying, it works.

Could you explain how you did this, please?


Error snippet below.
==========
rpm: RPM should not be used directly install RPM packages, use Alien instead!
rpm: However assuming you know what you are doing...
warning: /home/moses/photon/stage/PUBLISHRPMS/noarch/linux-api-headers-4.0.9-1.ph1tp2.noarch.rpm: Header V3 RSA/SHA1 Signature, key ID 66fd4949: NOKEY
warning: %post(bash-4.3-4.ph1tp2.x86_64) scriptlet failed, exit status 127
/bin/sh: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory
warning: %post(glibc-2.21-5.ph1tp2.x86_64) scriptlet failed, exit status 127

**Comment by sofar** [comment]
Those 2 errors are not relevant - while annoying, they don't influence the actual build (I've seen them too with succesefull builds

**Comment by moseslg** [comment]
Thanks Auke. I deployed a fresh Ubuntu desktop instead of the vagrant photon machine and the build was successful.
