### ISSUE TITLE
Photon Fresh Build: Exception: Cannot find filesystem rpm

### ISSUE THREAD

**Issue by leon-github** [vmware/photon#460]
Hi I'm seeing this issue on top of tree on a clean Ubuntu 14.04.3 LTS. Seems very easy to reproduce. Or does anything missed in the doc/build-photon.md? Any hints are appreciated.

2016-05-20 10:05:09,112 - Toolchain Utils - INFO - Building core tool chain packages.....
2016-05-20 10:05:09,121 - Toolchain Utils - INFO - Preparing build environment
2016-05-20 10:05:09,144 - Toolchain Utils - INFO - rpmbuild -ba --nocheck --define '_topdir /home/leonc/git/photon/stage/photonroot/build-core-toolchain/usr/src/photon' --define '_dbpath /home/leonc/git/photon/stage/photonroot/build-core-toolchain/var/lib/rpm' --define 'dist .ph1' --define 'photon_build_number 0d9d4f5' --define 'photon_release_version 1.0' /home/leonc/git/photon/SPECS/filesystem/filesystem.spec
2016-05-20 10:05:09,452 - Toolchain Utils - ERROR - Cannot find filesystem rpm
2016-05-20 10:05:09,453 - Toolchain Utils - ERROR - Unable to build tool chain.
Traceback (most recent call last):
File "/home/leonc/git/photon/support/package-builder/ToolChainUtils.py", line 185, in buildCoreToolChainPackages
self.installToolChainRPMS(chrootID)
File "/home/leonc/git/photon/support/package-builder/ToolChainUtils.py", line 201, in installToolChainRPMS
self.prepareBuildRoot(chrootID)
File "/home/leonc/git/photon/support/package-builder/ToolChainUtils.py", line 61, in prepareBuildRoot
raise Exception("Cannot find filesystem rpm")
Exception: Cannot find filesystem rpm
2016-05-20 10:05:09,453 - PackageManager - ERROR - Unable to build tool chain
2016-05-20 10:05:09,453 - PackageManager - ERROR - Cannot find filesystem rpm
2016-05-20 10:05:09,454 - /home/leonc/git/photon/stage/LOGS/Main - ERROR - Caught an exception
2016-05-20 10:05:09,454 - /home/leonc/git/photon/stage/LOGS/Main - ERROR - Cannot find filesystem rpm
Traceback (most recent call last):
File "/home/leonc/git/photon/support/package-builder/builder.py", line 136, in main
buildPackagesFromGivenJSONFile(options.inputJSONFile, options.buildOption, listBuildOptionPackages, options.pkgBuildOptionFile, logger, options.buildThreads)
File "/home/leonc/git/photon/support/package-builder/builder.py", line 296, in buildPackagesFromGivenJSONFile
pkgManager.buildPackages(listPackagesToBuild, listBuildOptionPackages, pkgBuildOptionFile, buildThreads)
File "/home/leonc/git/photon/support/package-builder/PackageManager.py", line 105, in buildPackages
self.buildToolChainPackages(listBuildOptionPackages, pkgBuildOptionFile, buildThreads)
File "/home/leonc/git/photon/support/package-builder/PackageManager.py", line 99, in buildToolChainPackages
self.buildToolChain()
File "/home/leonc/git/photon/support/package-builder/PackageManager.py", line 96, in buildToolChain
raise e
Exception: Cannot find filesystem rpm
make: *** [packages] Error 1

**Comment by leon-github** [comment]
Ok, found out that I need to correct /bin/sh symbol link from /bin/dash to /bin/bash.
