### ISSUE TITLE
Build from source fails

### ISSUE THREAD

**Issue by LukeMauldin** [vmware/photon#631]
On Ubuntu 16.10, following the build from source instructions at https://blogs.vmware.com/cloudnative/building-photon-os-from-source/ the build fails.

```
2017-04-13 14:14:29,561 - Toolchain Utils - INFO - Successfully installed all Tool Chain RPMS in Chroot:/home/mauldinl/photon/stage/photonroot/build-core-toolchain
2017-04-13 14:14:30,001 - Toolchain Utils - INFO - Building rpm's for package:bash
2017-04-13 14:14:30.078199: Downloading https://dl.bintray.com/vmware/photon_sources/1.0/bash-4.4.tar.gz...
2017-04-13 14:14:33,231 - Toolchain Utils - INFO - Copying... Source path :bash-4.4.tar.gz Source filename: /home/mauldinl/photon/stage/SOURCES/bash-4.4.tar.gz
2017-04-13 14:14:34,433 - Toolchain Utils - INFO - Copying... Source path :bash_completion Source filename: /home/mauldinl/photon/SPECS/bash/bash_completion
2017-04-13 14:14:34,455 - Toolchain Utils - INFO - Copying... Source path :bash-4.4.patch Source filename: /home/mauldinl/photon/SPECS/bash/bash-4.4.patch
2017-04-13 14:14:34,521 - Toolchain Utils - INFO - Building rpm....
2017-04-13 14:14:34,526 - Toolchain Utils - INFO - rpmbuild -ba --clean --define \"dist .ph1\" --nocheck --define \"KERNEL_RELEASE 2.ph1\" --define \"dist .ph1\" --define \"photon_build_number 83b804a\" --define \"KERNEL_VERSION 4.9.13\" --define \"kernelsubrelease .12577282\" --define \"photon_release_version 1.0\" /usr/src/photon/SPECS/bash.spec
2017-04-13 14:14:56,742 - Toolchain Utils - ERROR - Building rpm is failed /usr/src/photon/SPECS/bash.spec
2017-04-13 14:14:56,743 - Toolchain Utils - ERROR - Failed while building rpm:bash
2017-04-13 14:14:56,753 - Toolchain Utils - ERROR - Unable to build tool chain.
Traceback (most recent call last):
  File "/home/mauldinl/photon/support/package-builder/ToolChainUtils.py", line 97, in buildCoreToolChainPackages
    pkgUtils.buildRPMSForGivenPackage(package, chrootID, listBuildOptionPackages, pkgBuildOptionFile, destLogPath)
  File "/home/mauldinl/photon/support/package-builder/PackageUtils.py", line 197, in buildRPMSForGivenPackage
    raise e
Exception: RPM build failed
2017-04-13 14:14:56,784 - PackageManager - ERROR - Unable to build tool chain
2017-04-13 14:14:56,798 - PackageManager - ERROR - RPM build failed
2017-04-13 14:14:56,821 - /home/mauldinl/photon/stage/LOGS/Main - ERROR - Caught an exception
2017-04-13 14:14:56,831 - /home/mauldinl/photon/stage/LOGS/Main - ERROR - RPM build failed
Traceback (most recent call last):
  File "/home/mauldinl/photon/support/package-builder/builder.py", line 130, in main
    buildPackagesForAllSpecs(listBuildOptionPackages, options.pkgBuildOptionFile, logger, options.buildThreads, pkgInfoJsonFile)
  File "/home/mauldinl/photon/support/package-builder/builder.py", line 265, in buildPackagesForAllSpecs
    pkgManager.buildPackages(listPackages, listBuildOptionPackages, pkgBuildOptionFile, buildThreads)
  File "/home/mauldinl/photon/support/package-builder/PackageManager.py", line 145, in buildPackages
    self.buildToolChainPackages(listBuildOptionPackages, pkgBuildOptionFile, buildThreads)
  File "/home/mauldinl/photon/support/package-builder/PackageManager.py", line 128, in buildToolChainPackages
    self.buildToolChain()
  File "/home/mauldinl/photon/support/package-builder/PackageManager.py", line 125, in buildToolChain
    raise e
Exception: RPM build failed
Makefile:228: recipe for target 'packages' failed
make: *** [packages] Error 1
mauldinl@ubuntu-1610-vm:~/photon$ cat /proc/version
Linux version 4.8.0-46-generic (buildd@lcy01-16) (gcc version 6.2.0 20161005 (Ubuntu 6.2.0-5ubuntu12) ) #49-Ubuntu SMP Fri Mar 31 13:57:14 UTC 2017

```

**Comment by dthaluru** [comment]
@LukeMauldin  Can you please share logs. Logs will be available in stage/LOGS.

**Comment by LukeMauldin** [comment]
I have attached the log files.

[logs.tar.gz](https://github.com/vmware/photon/files/930910/logs.tar.gz)

**Comment by YustasSwamp** [comment]
mauldinl@ubuntu-1610-vm:~/photon$ tail /home/mauldinl/photon/stage/LOGS/build-bash/bash.log 
checking shared object configuration for loadable builtins... supported
configure: creating ./config.status
config.status: creating Makefile
awk: **symbol lookup error: /lib/libreadline.so.7: undefined symbol: UP**
config.status: error: could not create Makefile
error: Bad exit status from /var/tmp/rpm-tmp.ISaySk (%build)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.ISaySk (%build)
mauldinl@ubuntu-1610-vm:~/photon$

Looks like libreadline was built wrongly. Hard to say why.

try to remove readline rpm:
$ rm /home/mauldinl/photon/stage/RPMS/x86_64/readline-*
 and rerun:
$ sudo make all

**Comment by LukeMauldin** [comment]
[logs.tar.gz](https://github.com/vmware/photon/files/936792/logs.tar.gz)
After running the command above to remove readline, I am now getting this: `/bin/sh: error while loading shared libraries: libreadline.so.7: cannot open shared object file: No such file or directory`

Attaching logs.

**Comment by YustasSwamp** [comment]
got it. Lets restart the build from the beginning.

$ rm -rf stage
$ sudo make all

**Comment by ppadmavilasom** [comment]
@LukeMauldin are there still issues? is this okay to close?

**Comment by ppadmavilasom** [comment]
closing as abandoned. if still an issue, pls reopen
